jobs:
  action:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Start
        uses: actions/checkout@v2
      - name: Pull Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./check/run

name: Test

on:
  schedule:
    - cron: "10 */3 * * *"
